require_paths:
- "C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems"
- "C:/Program Files/SketchUp/SketchUp 2022/Tools"
- "C:/Users/Duncan/SketchUp Extensions/LayUp/src"

require:
- sketchup-api-stubs

reporters:
- rubocop
